### ISSUE TITLE
Nearby stations always empty

### ISSUE THREAD

**Issue by dpacassi** [timeforcoffee/timeforcoffee-android#29]
If I download and install the Android version of the app, the nearby stations list has only content when starting the app for the very first time.
Afterwards the list is always empty (tried force closing the app, restarting my phone, toggling Wi-Fi on/off, etc.).

I can't reproduce this behavior on Android Studio and more interestingly, if I clone the master branch (which should be the code base as the app in Google play) and load it to my phone via USB, then the list works again!

Well, except from a **random first station** the list works again.
Here a screenshot from a random station when opening the app in the Liip Zürich office:
https://www.dropbox.com/s/4tqyb1qq5s4jbt7/Screenshot_20171024-121435.png?dl=0

And this one from my home:
https://www.dropbox.com/s/ril1jg7una8i574/Screenshot_20171019-162530.png?dl=0

I invested a few minutes in trying to figure out where the bug is but my Android know-how is limited and I wasn't able to find any documentation.
Also, I recommend to create tags/releases when pushing a new version to the Google play store. That way it's easier to debug bugs on certain versions (and keeps a nice history :) )

**Comment by dpacassi** [comment]
The random first station seems to be a bug from the opendata.ch API, see https://github.com/OpendataCH/Transport/issues/176

Maybe we should check if the x/y coordinates are not null before insterting them to the station list.

**Comment by nico6ka** [comment]
Issue fixed with #31
