### ISSUE TITLE
[Android] some stations don't show transport information

### ISSUE THREAD

**Issue by keepthingsclean** [timeforcoffee/timeforcoffee-android#34]
On a seemingly random couple of stations, the spinner stays and no results for the connections are shown.

Stations not known to be working: Zürich Rotbuchstrasse, Zürich Milchbuck, Zürich Nordstrasse, Zürich Limmatplatz
Stations known to be working: Zürich Schaffhauserplatz, Zürich Sternen Oerlikon, Zürich Dammweg

Device: Google Pixel w/ Android 8

**Comment by dpacassi** [comment]
I'm affected by the same bug on the station "Zürich Seebach", other stations work so far.

Device: Samsung Galaxy S8+ w/ Android 7.0

**Comment by lucasardonini** [comment]
This should be fixed in https://github.com/timeforcoffee/timeforcoffee-android/pull/35
