### ISSUE TITLE
Watch: stations are not refreshed when opening the watch

### ISSUE THREAD

**Issue by nico6ka** [timeforcoffee/timeforcoffee-android#4]
When opening the watch app, we see the old list of stations (if we got one) before having the watch getting a new location and updating the list. We should clear the list on opening. (same thing myabe also apply to the Mobile app)

**Comment by lucasardonini** [comment]
I was not able to reproduce this bug because. when opening the app on the watch, the spinner is shown and the app loads the departures of the nearby station.
